# EMBEDDED SERVER 
server:
  port: 8086
  servlet:
    context-path: /sales
---    
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:as400://207.130.116.47;libraries=C82BPCSF
    username: BPCSSECOFM
    password: BPCSADMONM
  redis:
    host: localhost
    port: 6379
    url: redis://localhost:6380
    database: 1
    
# CORS configuration
application:
  allowedOrigin: http://localhost:4200, http://127.0.0.1:4200

microservice:
  managedb: http://qhdmglserwfs01:8080/managerbd/api/
  japanfile: http://qhdmglserwfs01:8080/japanfile/api/
  bpcs: http://qhdmglserwfs01:8080/bpcs/api/
  netcommerce: http://qhdmglserwfs01:8080/netcommerce/api

cors:
  origin:
    urione: http://qhdmglserwfs01.hdm.am.honda.com:8080
    uritwo: http://qhdmglserwfs01:8080