custom-ldap:
  base: DC=am,DC=mds,DC=honda,DC=com
  password: H2018in18
  referral: follow
  url: ldap://amhcldc02.am.mds.honda.com:389/
  userDn: CN=APP-THIRD-HOUSE-ADMIN,OU=Non-Person,OU=Users,OU=HDM,OU=Engineering,OU=Honda Global,DC=am,DC=mds,DC=honda,DC=com
  userSearchFilter: (sAMAccountName={0})
config:
  security:
    oauth:
      client:
        id: HDM_Honda
        secret: HDM_Honda_Secret_2021
      jwt:
        key: HDM_HONDA_KEY_DECIPHER_TOKENS_2021
application:
  enableCors: true
  allowedOrigin: http://phdmglserwfs01.hdm.am.honda.com:8080/, http://phdmglserwfs01:8080/, https://mss.dev.hondaweb.com

frontend:
  main-url: http://phdmglserwfs01.hdm.am.honda.com:8080/
  saml-view-url: http://phdmglserwfs01.hdm.am.honda.com:8080/saml/#/

backend:
  protocol: https
  servername: mss.hondaweb.com
  include-port: false