# EMBEDDED SERVER 
server:
  port: 8081
  servlet:
    context-path: /warrantiesmg
---    
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:postgresql://qhdmglcompsg01.hdm.am.honda.com:5433/qwmqmc01
    username: vjc80671
    password: ulJOEaMBTwlHzsXs
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:      hibernate:
        default_schema: wmqmcdb
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: SMTPGTW1.ham.am.honda.com        

app:
  file: 
    upload-dir: /images
    storage:
      mapping: file:~/images
# CORS configuration
application:
  allowedOrigin: http://localhost:4200, http://127.0.0.1:4200

#Security configuration (For enable token authentication remove this config)
config:
  security:
      oauth:
          jwt:
            enabled: false
              
logging:
  level:
    .: info
    org.springframework: INFO
notification:
    sender: HDM_Mxquote@hdm.honda.com