# EMBEDDED SERVER 
server:
  port: 8088
  servlet:
    context-path: /netcommerce
  
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:as400://207.130.116.47;libraries=C82BPCSF
    username: BPCSSECOFM
    password: BPCSADMONM
  redis:
    host: localhost
    port: 6379
    url: redis://localhost:6380
    database: 1
    
# CORS configuration
application:
  allowedOrigin: http://localhost:4200, http://127.0.0.1:4200
  
  
config:
  path-files: /app/files/
  
microservice:
  managedb: http://127.0.0.1:8084/managerbd/api/
  
netcommerce:
  user: apiventasmotos@netcommerce.mx
  pass: 8Vr_3Ha0_B1
  url-api: http://api.ventasmotos.honda.mx/auth/client/login
  secret-key: AMi9SMTLN5i1ruzCr65ElFK2Hz2BO2neWanYSxFB/3I=
  encode: http://qhdmglserwfs01/warrantiesapi/index.php
cors:
  origin:
    urione: http://localhost:4200
    uritwo: http://127.0.0.1:4200