# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  redis:
    host: localhost
    port: 6379
    url: redis://localhost:6379
    database: 1
cors:
  origin:
    urione: http://qhdmglserwfs01.hdm.am.honda.com:8080
    uritwo: http://qhdmglserwfs01:8080