# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:as400://207.130.116.47;libraries=C82BPCSF
    username: BPCSSECOFM
    password: BPCSADMONM
  redis:
    host: localhost
    port: 6379
    url: redis://localhost:6380
    database: 1
    
# CORS configuration
application:
  allowedOrigin: http://phdmglserwfs01.hdm.am.honda.com:8080, http://phdmglserwfs01:8080
  
  
config:
  path-files: /app/files/
  
microservice:
  managedb: http://phdmglserwfs01:8080/managerbd/api/
  
netcommerce:
  user: apiventasmotos@netcommerce.mx
  pass: 8Vr_3Ha0_B1
  url-api: http://api.ventasmotos.honda.mx/auth/client/login
  secret-key: AMi9SMTLN5i1ruzCr65ElFK2Hz2BO2neWanYSxFB/3I=
  encode: http://phdmglserwfs01/warrantiesapi/index.php
cors:
  origin:
    urione: http://phdmglserwfs01.hdm.am.honda.com:8080
    uritwo: https://mss.hondaweb.com