# EMBEDDED SERVER 
server:
  port: 8086
  servlet:
    context-path: /sales

spring:
  datasource:
    url: jdbc:as400://207.130.116.47;libraries=C82BPCSF
    username: BPCSSECOFM
    password: BPCSADMONM
  redis:
    host: localhost
    port: 6379
    url: redis://localhost:6380
    database: 1

microservice:
  managedb: http://localhost:8084/managerbd/api
  bpcs: http://qhdmglserwfs01:8080/bpcs/api
  netcommerce: http://localhost:8088/netcommerce/api
  
cors:
  origin:
    urione: http://localhost:4200
    uritwo: http://127.0.0.1:4200