# EMBEDDED SERVER 
server:
  port: 8081
  servlet:
    context-path: /warrantiesmg
---    
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource: 
    jndi-name: java:jboss/datasources/jBossWarrantiesDS-qa

# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: wmqmcdb
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: SMTPGTW1.ham.am.honda.com

# APPLICATION file uploader propierties
app:
  file: 
    upload-dir: /images
    storage:
      mapping: file:~/images

#Security configuration (For enable token authentication remove this config)
config:
  security:
      oauth:
          jwt:
            enabled: false

# CORS configuration
application:
  allowedOrigin: http://qhdmglserwfs01:8080, http://qhdmglserwfs01.hdm.am.honda.com:8080
  
logging:
  level:
    .: info
    org.springframework: INFO
notification:
    sender: HDM_Mxquote@hdm.honda.com